### ISSUE TITLE
Modofication des coordonnateurs dans le mandat

### ISSUE THREAD

**Issue by mariehelenefaucher** [infsy/Kentel#4]
Holà!

Dans un mandat, je ne suis pas en mesure de modifier le ou les coordonnateurs en place. Exemple, si tu prends le mandat 7349, j'aimerais retirer certains coordonateurs qui ne sont actuellement plus chez-nous. Est-ce que tu pourrais ajouter le champ coodonnateur lorsqu'on sélectionne Modifier le mandat?

Merci !!! ;-)

**Comment by infsy** [comment]
resolved in f061de55c357253667699a550556c16e27ca410c

Your environment is already updated.
